### ISSUE TITLE
Homebrew formula does not install a JDK

### ISSUE THREAD

**Issue by furudean** [kobaltcore/renkit#12]
```
> brew install kobaltcore/homebrew-renkit/renkit
> renutil install 8.2.0
Error: JAVA_HOME is not set. Please check if you need to install OpenJDK 21
```

I don't see anything in the instructions about you needing to install and provide a Java installation to the env. This might just be a simple docs issue, but I figured this would be worth mentioning.

**Comment by kobaltcore** [comment]
Yeah, thanks for the heads-up, it's indeed a docs issue. I'm so deep into things that the Java dependency was always implicit for me, given that you also need the same thing when you use Ren'Py normally, but it's definitely worth making explicit.

**Comment by kobaltcore** [comment]
I've made `openjdk@21` a dependency for the Homebrew formula (at least for the next release), though this is a bit of a challenge, since Ren'Py may rely on either v8 or v21 depending on which version of Ren'Py is going to be in use. In this case, I'm opting in favor of the 'current thing', and will update the required Java version whenever Ren'Py updates it.
For older version, an older version must be manually installed and referenced, though. Maybe I can figure out a more automatic way of finding relevant versions at some point.

**Comment by furudean** [comment]
Thanks for looking into this!
