### ISSUE TITLE
Is the "Linux-only" build option supported?

### ISSUE THREAD

**Issue by SergioAlonsoJr** [kobaltcore/renkit#4]
![image](https://user-images.githubusercontent.com/4298411/151709765-bc8f994b-4159-462b-84f0-98fc3494e4ce.png)
Using the Ren'py interface I can make a build exclusive for Linux, but I can't figure it out how to make the "Linux-only" build with renconstruct

**Comment by kobaltcore** [comment]
Yep, that one wasn't supported in renconstruct yet, but I have just added it.
There are a couple builds I still need to test a bit more, notably the iOS, Web and Steam builds, since those are kinda finicky, but the Linux build I just enabled should work fine. Was likely an oversight since it didn't exist when I first built this toolkit.

The new release is available [here](https://github.com/kobaltcore/renkit/releases/tag/v1.1.3).

**Comment by SergioAlonsoJr** [comment]
Thanks a lot for the patch. I think I can now use your library well :)
