### ISSUE TITLE
Windows Defender thinks this is a trojan

### ISSUE THREAD

**Issue by SergioAlonsoJr** [kobaltcore/renkit#6]
I downloaded the renkit and tried to use it, but Windows 11 says it's: Trojan:Win32/Wacatac.B!ml

**Comment by kobaltcore** [comment]
Unfortunately this is a known issue with compiled Nim software, presumably because it uses a very recent GCC, which some Antivirus programs don't like. Alas, I do not have the ability to fix this on my end, as it's a compiler issue at the moment. there are plans from the Nim folks to resolve this in the future, but at the moment we will have to deal with it.
